/*
 * Copyright (C) 2022 The Holodeck B2B Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Affero GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.holodeckb2b.bdxr.smp.server.db.entities;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

import org.holodeckb2b.bdxr.common.datamodel.Extension;
import org.holodeckb2b.bdxr.common.datamodel.Identifier;
import org.holodeckb2b.bdxr.smp.server.datamodel.Certificate;
import org.holodeckb2b.bdxr.smp.server.datamodel.Endpoint;
import org.holodeckb2b.bdxr.smp.server.datamodel.TransportProfile;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.ManyToOne;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Is the JPA entity for storing the {@link Endpoint} meta-data in the database.
 *
 * @author Sander Fieten (sander at holodeck-b2b.org)
 */
@Entity(name = "Endpoint")
@Getter
@NoArgsConstructor
public class EndpointEntity extends BaseMetadataRegistrationEntity<Long> implements Endpoint {
	private static final long serialVersionUID = -2225922488197162436L;

	@ManyToOne(optional = false)
	protected TransportProfileEntity	transportProfile;

	@Setter
	@Column
	protected	String	url;

	@Setter
	@ElementCollection(targetClass = EmbeddedCertificate.class)
	@CollectionTable(name = "EP_CERTIFICATES")
	protected List<Certificate>	certificates = new ArrayList<>();

	@Setter
	@Column
	protected ZonedDateTime	serviceActivationDate;

	@Setter
	@Column
	protected ZonedDateTime	serviceExpirationDate;

	@Setter
	@Column
	protected String	description;

	@Setter
	@Column
	protected String	contactInfo;

	@Override
	public Long getId() {
		return oid;
	}
	
	/*
	 * As the id is generated by the JPA, we don't want to set it manually	
	 */
	@Override
	public void setId(Long id) {
	}
	
	@Override
	public Identifier getTransportProfileId() {
		return transportProfile == null ? null : transportProfile.getId();
	}
	
	@Override
	public void setTransportProfile(TransportProfile transportProfile) {
		if (!(transportProfile instanceof TransportProfileEntity) 
			| ((TransportProfileEntity) transportProfile).getOid() == null)
			throw new IllegalArgumentException("Unmanaged TransportProfile object");
		this.transportProfile = (TransportProfileEntity) transportProfile;
	}
	
	@Override
	public URL getEndpointURL() {
		try {
			return url != null ? new URL(url) : null;
		} catch (MalformedURLException ex) {
			throw new IllegalStateException("Invalid URL (" + url + ") for Endpoint oid=" + oid.toString());
		}
	}

	@Override
	public void setEndpointURL(URL url) {
		this.url = url == null ? null : url.toString();
	}
	
	@Override
	public void addCertificate(org.holodeckb2b.bdxr.smp.datamodel.Certificate cert) {
		certificates.add(new EmbeddedCertificate(cert));		
	}
	
	@Override
	public void removeCertificate(Certificate cert) {
		certificates.remove(cert);		
	}
	
	@Override
	public List<Extension<?>> getExtensions() {
		return null;
	}
}
